add new font cache file (dont remove old one in case they downgrade)
eventespresso/eea-utf8-message-template-variations pull request #1
Opened 2018-09-21 16:35 UTC by mnelson4

We're upgrading DOMPDF in EE core to 0.8.2, where the font cache file's filetype is just `.php` instead of `.dist.php`.
In order for this add-on to correctly inform DOMPDF of other font files, we need to update the file's filetype.
In this commit, I just added a new font cache file. I didn't remove the old one so this version of the add-on will continue to work with EE 4.9.66 and lower

2018-09-25 14:38 UTC, knazart requested changes
Wait, the `dompdf_font_family_cache` is still `.dist.php` in the new version. Am I missing something ?

2018-09-25 16:48 UTC, mnelson4 commented
> Wait, the dompdf_font_family_cache is still .dist.php in the new version. Am I missing something ?

I suspect you skimmed over my last comment where I said

> In this commit, I just added a new font cache file. I didn't remove the old one so this version of the add-on will continue to work with EE 4.9.66 and lower

Or did that only make sense in my head? :stuck_out_tongue:

2018-09-25 17:52 UTC, knazart commented
> I suspect you skimmed over my last comment

No, I didn't skimmed over. I read it a few times. Still a bit confused, sorry. Where do you see that "the font cache file's filetype is just `.php` instead of `.dist.php`" ?

2018-09-25 21:00 UTC, mnelson4 commented
No worries, I often don't make a lot of sense. I mentioned it at the end of this comment: https://github.com/eventespresso/eea-utf8-message-template-variations/pull/1#issue-217339167
But the point is: the old dompdf is looking for `dompdf_font_cache.dist.php`, whereas the new one is looking for `dompdf_font_cache.php`. If it's easy, we may as well make this add-on compatible with both versions of dompdf, so I didn't remove the old one (`.dist.php`), I just added the new one (`.php`).

2018-09-26 11:00 UTC, knazart commented
Yes, I get that. The confusion was that the `loadFontFamilies()` method is still looking for the same file: `$file = $rootDir . "/lib/fonts/dompdf_font_family_cache.dist.php";` and it is still originally present under `../lib/fonts/`.
Although now I also see this: `const CACHE_FILE = "dompdf_font_family_cache.php";`. So it seems that it first looks for the `.dist.php` and then defaults to the `CACHE_FILE` - makes sense now.

2018-09-26 11:01 UTC, knazart approved these changes

2018-09-26 16:49 UTC, mnelson4 commented
ahhh kk.
So @Pebblo (I think you most recently worked with the DOMPDF UTF8 add-on) would you be able to confirm his still works with EE master and https://github.com/eventespresso/event-espresso-core/pull/699?

2018-09-28 18:57 UTC, joshfeck commented
I went ahead and tested this because I was already testing eventespresso/event-espresso-core#699 and testing this PR was part of that testing checklist. This is ready to be merged.

2018-09-28 21:18 UTC, mnelson4 commented
Great thanks @joshfeck

2018-09-28 21:18 UTC, merged